# If 'awesome-app dev' is not working with this Awesome.toml, rename or delete it, 
# and run again 'awesome-app dev' and this file will be generated again.

# Note 1: Runners executed in order. Default is blocking except if concurrent = true.
# Note 2: end_all_on_exit = true, for concurrent runners tells to end the session if this specific process ends.
# Note 3: Eventually, [[runners.build]] will also be available. Splitting the two makes it less convoluted and more flexible.

[[runners.dev]]
name = "npm_install"
cmd = "npm"
args = ["install"]

[[runners.dev]]
name = "tauri_icons"
cmd = "npm"
args = ["run", "tauri", "icon", "src-tauri/icons/app-icon.png"]

[[runners.dev]]
name = "cargo_build"
working_dir = "src-tauri/"
cmd = "cargo"
args = ["build"]

[[runners.dev]]
name = "pcss"
cmd = "npm"
args = ["run", "pcss", "--", "-w"]
concurrent = true 
# if this process exit, end the dev session
end_all_on_exit = true

[[runners.dev]]
name = "rollup"
cmd = "npm"
args = ["run", "rollup", "--", "-w"]
concurrent = true
end_all_on_exit = true

[[runners.dev]]
name = "localhost"
cmd = "npm"
args = ["run", "localhost"]
concurrent = true
end_all_on_exit = true

[[runners.dev]]
name = "tauri_dev"
wait_before = 2000 # wait in ms, before getting called
cmd = "npm"
args = ["run", "tauri", "dev"]
concurrent = true
end_all_on_exit = true